sudo: required
dist: trusty
language: node_js

node_js:
- '6'
- '7'

before_install:
  - sudo apt-get install libsasl2-dev libssl-dev

install:
  - npm install

script:
  - npm run lint
  - npm run test